as_list = [
["Igel", "weak", "masculine", "animal"],
["Schiff", "weak", "neutral", None],
["Blase", "weak", "feminine", None],
["Kanone", "weak", "feminine", None],
["Apfeltasche", "weak", "feminine", None],
["Atomreaktor", "weak", "masculine", None],
["Hase", "weak", "masculine", "animal"],
["Nase", "weak", "feminine", None],
["Wurst", "strong", "feminine", None],
["Fenster", "weak", "neutral", None],
["Banane", "weak", "feminine", None],
["Vogel", "strong", "masculine", "animal"],
["Ampel", "weak", "feminine", None],
["Kreisel", "weak", "masculine", None],
["Insel", "weak", "feminine", None],
["Pinsel", "weak", "masculine", None],
["Eichel", "weak", "feminine", None],
["Stuhl", "strong", "masculine", None],
["Ast", "strong", "masculine", None],
["Christbaumkugel", "weak", "feminine", None],
["Auto", "weak", "neutral", None],
["PC", "weak", "masculine", None],
["Gummistiefel", "weak", "masculine", None],
["Amtsarzt", "strong", "masculine", "person"],
["General", "strong", "masculine", "person"],
["Bruchpilot", "weak", "masculine", "person"],
["Handgranate", "weak", "feminine", None],
["Klobürste", "weak", "feminine", None],
["Bügeleisen", "weak", "neutral", None],
["Abendessen", "weak", "neutral", None],
["Krokodil", "weak", "neutral", "animal"],
["Hochzeitskleid", "weak", "neutral", None],
["Kartoffelschäler", "weak", "masculine", None],
["Leiche", "weak", "feminine", None],
["Triebwerk", "weak", "neutral", None],
["Sauerkraut", "weak", "neutral", None, True],
["Schmierseife", "weak", "neutral", None, True],
["Kokain", "weak", "neutral", None, True],
["Bier", "weak", "neutral", None, True],
["Geist", "weak", "masculine", "mythical creature"],
["Einhorn", "strong", "neutral", "mythical creature"],
["Drache", "weak", "masculine", "mythical creature"],
]