as_list = [
["auf", "local", ["stay", "move"], ["dative", "accusative"]],
["hinter", "local", ["stay", "move"], ["dative", "accusative"]],
["unter", "local", ["stay", "move"], ["dative", "accusative"]],
["neben", "local", ["stay", "move"], ["dative", "accusative"]],
["bei", "local", ["stay"], ["dative"]],
["um", "local", ["move"], ["accusative"]],
["in", ["local", "temporal"], ["stay", "move"], ["dative", "accusative"]],
["vor", ["local", "temporal"], ["stay", "move"], ["dative", "accusative"]],
["an", ["local", "temporal"], ["move"], ["accusative"]],
["nach", "temporal", [], ["dative"]],
["während", "temporal", [], ["dative"]],
["seit", "temporal", [], ["dative"]],
["für", "neutral", [], ["accusative"]],
["mit", "modal", [], ["dative"]],
["bis zu", ["local", "temporal"], [], ["dative"]],
]