list_of_prepositions = [
["auf", "local", ["stay", "move"], ["dative", "accusative"]],
["hinter", "local", ["stay", "move"], ["dative", "accusative"]],
["unter", "local", ["stay", "move"], ["dative", "accusative"]],
["neben", "local", ["stay", "move"], ["dative", "accusative"]],
["bei", "local", ["stay"], ["dative"]],
["um", "local", ["move"], ["accusative"]],
["in", "local", ["stay", "move"], ["dative", "accusative"]],
["vor", ["local", "temporal"], ["stay", "move"], ["dative", "accusative"]],
["an", "local", ["move"], ["accusative"]],
["nach", "temporal", [], ["dative"]],
["während", "temporal", ["period"], ["dative"]],
["seit", "temporal", [], ["dative"]],
["bis zu", "temporal", [], ["dative"]],
["nach", "temporal", [], ["dative"]],
["in", "temporal", ["period"], ["dative"]],
]