

as_list = [
["gefallen", "strong", 2, "dative", ["patient", "experiencer"], "stay"],
["schneien", "weak", 0, 0, 0, "stay"],
["regnen", "weak", 0, 0, 0, "stay", True],
["vergessen", "strong", 2, "accusative", ["agent", "patient"], "stay"],
["lesen", "strong", 1, 0, ["agent"], "stay", True],
["saufen", "strong", 1, 0, ["agent"], "stay", True],
["enftühren", "weak", 2, "accusative", ["agent", "patient"], "move"],
["sehen", "strong", 2, "accusative", ["experiencer", "patient"], "stay"],
["vernichten", "weak", 2, "accusative", ["agent", "patient"], "stay"],
["wandern", "weak", 1, 0, ["agent"], "move"],
["auflauern", "weak", 1, 0, ["agent"], "stay", True],
["spielen", "weak", 1, 0, ["agent"], "stay", True],
["schlafen", "strong", 1, 0, ["agent"], "stay", False, ["mit", "living_thing"]],
["vergeben", "strong", 2, "dative",  ["agent", "experiencer"], "stay", True],
["sprechen", "strong", 1, 0, ["agent"], "stay", False, ["mit", "person"]],
["begraben", "strong", 2, "accusative", ["agent", "patient"], "stay"],
["verstecken", "weak", 2, "accusative", ["agent", "patient"], "stay", False, ["vor", "living_thing"]],
["riechen", "weak", 2, "accusative", ["experiencer", "patient"], "stay"],
["verkaufen", "weak", 2, "accusative", ["agent", "patient"], "stay", False, ["an", "person"]],
["zusehen", "strong", 2, "dative", ["agent", "patient"], "stay", False, ["bei", "activity"]],
["nachmachen", "weak", 2, "accusative", ["agent", "patient"], "stay"],
["abschlecken", "weak", 2, "accusative", ["agent", "patient"], "stay"],
["einsperren", "weak", 2, "accusative", ["agent", "patient"], "stay"],
["auslachen", "weak", 2, "accusative", ["agent", "experiencer"], "stay", False, ["für", "anything"]],
["zerstückeln", "weak", 2, "accusative", ["agent", "patient"], "stay"],
["einpacken", "weak", 2, "accusative", ["agent", "patient"], "stay"],
["austricksen", "weak", 2, "accusative", ["agent", "experiencer"], "stay"],
["fliegen", "weak", 1, 0, ["agent"], "move"],
["zeigen", "weak", 3, "dative", ["agent", "experiencer", "patient"], "stay"],
["geben", "strong", 3, "dative", ["agent", "experiencer", "patient"], "stay"],
["anzünden", "weak", 2, "accusative", ["agent", "patient"], "stay"],
["jagen", "weak", 2, "accusative", ["agent", "patient"], ["stay", "move"]],
["zeichnen", "weak", 1, "accusative", ["agent", "patient"], ["stay"], True],
["denken", "weak", 1, 0, ["agent"], ["stay"], False, ["an", "anything"]],
#["warten", "weak", 1, 0, ["agent"], ["stay"], False, ["auf", "anything"]],
]