list_of_verbs = [
["gefallen", "strong", 2, "dative", ["patient", "experiencer"], "stay"],
["schneien", "weak", 0, 0, 0, "stay"],
["regnen", "weak", 0, 0, 0, "stay"],  
["vergessen", "strong", 2, "accusative", ["agent", "patient"], "stay"],
["lesen", "strong", 1, 0, ["agent"], "stay"],
["saufen", "strong", 1, 0, ["agent"], "stay"],
["enftühren", "weak", 2, "accusative", ["agent", "patient"], "move"],
["sehen", "strong", 2, "accusative", ["experiencer", "patient"], "stay"],
["vernichten", "weak", 2, "accusative", ["agent", "patient"], "stay"],
["wandern", "weak", 1, 0, ["agent"], "move"],
["lauern", "weak", 1, 0, ["agent"], "stay"],
["spielen", "weak", 1, 0, ["agent"], "stay"],
["schlafen", "strong", 1, 0, ["agent"], "stay"],
["vergeben", "strong", 2, "dative",  ["agent", "experiencer"], "stay"],
["sprechen", "strong", 1, 0, ["agent"], "stay"],
["begraben", "strong", 2, "accusative", ["agent", "patient"], "stay"],
["verstecken", "weak", 2, "accusative", ["agent", "patient"], "stay"],
["riechen", "weak", 2, "accusative", ["experiencer", "patient"], "stay"],
["verkaufen", "weak", 2, "accusative", ["agent", "patient"], "stay"],
["zusehen", "strong", 2, "dative", ["agent", "patient"], "stay"],
["nachmachen", "weak", 2, "accusative", ["agent", "patient"], "stay"],
["abschlecken", "weak", 2, "accusative", ["agent", "patient"], "stay"],
["einsperren", "weak", 2, "accusative", ["agent", "patient"], "stay"],
["auslachen", "weak", 2, "accusative", ["agent", "experiencer"], "stay"],
["zerstückeln", "weak", 2, "accusative", ["agent", "patient"], "stay"],
["einpacken", "weak", 2, "accusative", ["agent", "patient"], "stay"],
["austricksen", "weak", 2, "accusative", ["agent", "experiencer"], "stay"],
["fliegen", "weak", 1, 0, ["agent"], "move"],
["zeigen", "weak", 3, "dative", ["agent", "experiencer", "patient"], "stay"],
["geben", "strong", 3, "dative", ["agent", "experiencer", "patient"], "stay"], #maybe add annotation that no person can be chosen as object2
]