vowels = ["a", "e", "i", "o", "u", "A", "E", "I", "O", "U"]
conjugation_exceptions = ["laufen", "saufen", "stehlen", "sehen", "zusehen" , "lesen", "empfehlen", "geschehen", "befehlen", "wissen"]
persons = ["1st", "2nd", "3rd"]
genera = ["masculine", "feminine", "neutral"]
numbers = ["singular", "plural"]
article_types = ["definite", "indefinite"]
detached_affixes = ["zu", "aus", "ab", "ein", "nach"]
list_of_preposition_types = ["local"]
sentence_modes = ["declarative", "interrogative"]
closing_punctuation_marks = [".", "?"]
dative_with_n_plural_only = ["Igel", "Vogel"]
dative_with_en = ["Hase", "Bruchpilot"]
accusative_with_en = ["Hase","Bruchpilot"]
nouns_without_plural_form = ["Abendessen"]
melt_words = {"an dem":"am", "bei dem":"beim", "in dem":"im", "von dem":"vom", "zu dem":"zum", "an das":"ans", "in das":"ins", "zu der":"zur"}
interrogative_words = ["warum", "weshalb", "wieso", "wann", "wo", "wer", "was", "wie"]

