list_of_person_names = [
["Robert", "masculine"],
["Helmut", "masculine"],
["Berthold", "masculine"],
["Donald J. Trump", "masculine"],
["Violetta", "feminine"],
["Biene Maja", "feminine"],
["Berta", "feminine"],
["Chuck Norris", "masculine"],
["Heidi Klum", "feminine"],
["Angela Merkel", "feminine"],
["James Bond", "masculine"],
["Dschingis Khan", "masculine"],
["Käpt'n Blaubär", "masculine"],
["Meister Proper", "masculine"],
["Käpt'n Iglo", "masculine"],
["Kleopatra", "feminine"],
["Angela Merkel", "feminine"],
["Kim Kardashian", "feminine"],
["Greta Thunberg", "feminine"],
]