list_of_verbs = [
["gefallen", "strong", 2, "dative", ["patient", "experiencer"]],
["schneien", "weak", 0, 0, 0],
["regnen", "weak", 0, 0, 0],  
["vergessen", "strong", 2, "accusative", ["agent", "patient"]],
["lesen", "strong", 1, 0, ["agent"]],
["saufen", "strong", 1, 0, ["agent"]],
{"word":"enftühren", "strong_or_weak":"weak", 2, "accusative", ["agent", "patient"]],
["sehen", "strong", 2, "accusative", ["experiencer", "patient"]],
["vernichten", "weak", 2, "accusative", ["agent", "patient"]],
["wandern", "weak", 1, 0, ["agent"]],
["lauern", "weak", 1, 0, ["agent"]],
["spielen", "weak", 1, 0, ["agent"]],
["schlafen", "strong", 1, 0, ["agent"]],
["vergeben", "strong", 2, "dative",  ["agent", "patient"]],
["sprechen", "strong", 1, 0, ["agent"]],
["begraben", "strong", 2, "accusative", ["agent", "patient"]],
["verstecken", "weak", 2, "accusative", ["agent", "patient"]],
["riechen", "weak", 2, "accusative", ["experiencer", "patient"]],
["verkaufen", "weak", 2, "accusative", ["agent", "patient"]],
["zusehen", "strong", 2, "dative", ["agent", "patient"]],
["nachmachen", "weak", 2, "accusative", ["agent", "patient"]],
["abschlecken", "weak", 2, "accusative", ["agent", "patient"]],
["einsperren", "weak", 2, "accusative", ["agent", "patient"]],
["auslachen", "weak", 2, "accusative", ["agent", "patient"]],
["zerstückeln", "weak", 2, "accusative", ["agent", "patient"]],
["einpacken", "weak", 2, "accusative", ["agent", "patient"]],
["austricksen", "weak", 2, "accusative", ["agent", "experiencer"]],
]