list_of_verbs = [
{"word":"gefallen", "strong_or_weak":"strong", "valency":2, "object_case":"dative", "θrolls":["patient", "experiencer"]},
{"word":"schneien", "strong_or_weak":"weak", "valency":0, "object_case":0, "θrolls":0},
{"word":"regnen", "strong_or_weak":"weak", "valency":0, "object_case":0, "θrolls":0},  
{"word":"vergessen", "strong_or_weak":"strong", "valency":2, "object_case":"accusative", "θrolls":["agent", "patient"]},
{"word":"lesen", "strong_or_weak":"strong", "valency":1,"object_case":0, "θrolls":["agent"]},
{"word":"saufen", "strong_or_weak":"strong", "valency":1,"object_case":0, "θrolls":["agent"]},
{"word":"enftühren", "strong_or_weak":"weak", "valency":2, "object_case":"accusative", "θrolls":["agent", "patient"]},
{"word":"sehen", "strong_or_weak":"strong", "valency":2, "object_case":"accusative", "θrolls":["experiencer", "patient"]},
{"word":"vernichten", "strong_or_weak":"weak", "valency":2, "object_case":"accusative", "θrolls":["agent", "patient"]},
{"word":"wandern", "strong_or_weak":"weak", "valency":1,"object_case":0, "θrolls":["agent"]},
{"word":"lauern", "strong_or_weak":"weak", "valency":1,"object_case":0, "θrolls":["agent"]},
{"word":"spielen", "strong_or_weak":"weak", "valency":1,"object_case":0, "θrolls":["agent"]},
{"word":"schlafen", "strong_or_weak":"strong", "valency":1,"object_case":0, "θrolls":["agent"]},
{"word":"vergeben", "strong_or_weak":"strong", "valency":2, "object_case":"dative",  "θrolls":["agent", "patient"]},
{"word":"sprechen", "strong_or_weak":"strong", "valency":1,"object_case":0, "θrolls":["agent"]},
{"word":"begraben", "strong_or_weak":"strong", "valency":2, "object_case":"accusative", "θrolls":["agent", "patient"]},
{"word":"verstecken", "strong_or_weak":"weak", "valency":2, "object_case":"accusative", "θrolls":["agent", "patient"]},
{"word":"riechen", "strong_or_weak":"weak", "valency":2, "object_case":"accusative", "θrolls":["experiencer", "patient"]},
{"word":"verkaufen", "strong_or_weak":"weak", "valency":2, "object_case":"accusative", "θrolls":["agent", "patient"]},
{"word":"zusehen", "strong_or_weak":"strong", "valency":2, "object_case":"dative", "θrolls":["agent", "patient"]},
{"word":"nachmachen", "strong_or_weak":"weak", "valency":2, "object_case":"accusative", "θrolls":["agent", "patient"]},
{"word":"abschlecken", "strong_or_weak":"weak", "valency":2, "object_case":"accusative", "θrolls":["agent", "patient"]},
{"word":"einsperren", "strong_or_weak":"weak", "valency":2, "object_case":"accusative", "θrolls":["agent", "patient"]},
{"word":"auslachen", "strong_or_weak":"weak", "valency":2, "object_case":"accusative", "θrolls":["agent", "patient"]},
{"word":"zerstückeln", "strong_or_weak":"weak", "valency":2, "object_case":"accusative", "θrolls":["agent", "patient"]},
{"word":"einpacken", "strong_or_weak":"weak", "valency":2, "object_case":"accusative", "θrolls":["agent", "patient"]},
{"word":"austricksen", "strong_or_weak":"weak", "valency":2, "object_case":"accusative", "θrolls":["agent", "experiencer"]},
]